# Generated by Django 5.1.3 on 2024-12-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='adaptacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='comunicacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='resolucion_problemas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='trabajo_en_equipo',
            field=models.IntegerField(default=0),
        ),
    ]
